/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip_project;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ayush
 */
public class programming extends javax.swing.JFrame {

    /**
     * Creates new form programming
     */
    public programming() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Qbasic = new javax.swing.JLabel();
        nbeans = new javax.swing.JLabel();
        python = new javax.swing.JLabel();
        cplus = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        cbq = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Qbasic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip_project/qbasic.png"))); // NOI18N
        getContentPane().add(Qbasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        nbeans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip_project/netbeans-6-5.png"))); // NOI18N
        getContentPane().add(nbeans, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 280, -1));

        python.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip_project/python.png"))); // NOI18N
        getContentPane().add(python, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        cplus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip_project/c--logo-icon-17.png"))); // NOI18N
        getContentPane().add(cplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip_project/c.png"))); // NOI18N
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Select item");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel3.setText("Programming softwares");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 290, -1));

        cb1.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qbasic", "netbeans", "python", "c++", "c" }));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb1MouseClicked(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        cb1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb1PropertyChange(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 300, 40));

        cbq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbqItemStateChanged(evt);
            }
        });
        cbq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbqMouseClicked(evt);
            }
        });
        getContentPane().add(cbq, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 50, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Price per item");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Net amount");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        lb2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 110, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        lb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 110, 30));

        jButton6.setBackground(new java.awt.Color(255, 0, 51));
        jButton6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Add to cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip_project/3379d420-6679-4b55-a85c-f2c2a46740d9.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        // TODO add your handling code here:
        int i=cb1.getSelectedIndex();
        int y=Integer.parseInt((String) cbq.getSelectedItem());
        int z=0,x=0;
        python.setVisible(false);
        Qbasic.setVisible(false);
        nbeans.setVisible(false);
        cplus.setVisible(false);
        c.setVisible(false);
        switch(i)
        {
            case 0:Qbasic.setVisible(true);
            x=299;
            break;
            case 1:nbeans.setVisible(true);x=499;
            break;
            case 2:python.setVisible(true);x=455;
            break;
            case 3:cplus.setVisible(true);x=449;
            break;
            case 4:c.setVisible(true);x=399;
            break;
            default:Qbasic.setVisible(true);x=299;
            break;}
        lb1.setText(Integer.toString(x));
        z=x*y;
        lb2.setText(Integer.toString(z));
    }//GEN-LAST:event_cb1ItemStateChanged

    private void cb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb1MouseClicked
        // TODO add your handling code here:
        int i=cb1.getSelectedIndex();
        int y=Integer.parseInt((String) cbq.getSelectedItem());
        int z=0,x=0;
        python.setVisible(false);
        Qbasic.setVisible(false);
        nbeans.setVisible(false);
        cplus.setVisible(false);
        c.setVisible(false);
        switch(i)
        {
            case 0:Qbasic.setVisible(true);
            x=299;
            break;
            case 1:nbeans.setVisible(true);x=499;
            break;
            case 2:python.setVisible(true);x=455;
            break;
            case 3:cplus.setVisible(true);x=449;
            break;
            case 4:c.setVisible(true);x=399;
            break;
            default:Qbasic.setVisible(true);x=299;
            break;}
        lb1.setText(Integer.toString(x));
        z=x*y;
        lb2.setText(Integer.toString(z));
    }//GEN-LAST:event_cb1MouseClicked

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1PropertyChange

    private void cbqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbqItemStateChanged
        // TODO add your handling code here:
        int i=cb1.getSelectedIndex();
        int y=Integer.parseInt((String) cbq.getSelectedItem());
        int z=0,x=0;
        python.setVisible(false);
        Qbasic.setVisible(false);
        nbeans.setVisible(false);
        cplus.setVisible(false);
        c.setVisible(false);
        switch(i)
        {
            case 0:Qbasic.setVisible(true);
            x=299;
            break;
            case 1:nbeans.setVisible(true);x=499;
            break;
            case 2:python.setVisible(true);x=455;
            break;
            case 3:cplus.setVisible(true);x=449;
            break;
            case 4:c.setVisible(true);x=399;
            break;
            default:Qbasic.setVisible(true);x=299;
            break;}
        lb1.setText(Integer.toString(x));
        z=x*y;
        lb2.setText(Integer.toString(z));
    }//GEN-LAST:event_cbqItemStateChanged

    private void cbqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbqMouseClicked
        // TODO add your handling code here:
        int i=cb1.getSelectedIndex();
        int y=Integer.parseInt((String) cbq.getSelectedItem());
        int z=0,x=0;
        python.setVisible(false);
        Qbasic.setVisible(false);
        nbeans.setVisible(false);
        cplus.setVisible(false);
        c.setVisible(false);
        switch(i)
        {
            case 0:Qbasic.setVisible(true);
            x=299;
            break;
            case 1:nbeans.setVisible(true);x=499;
            break;
            case 2:python.setVisible(true);x=455;
            break;
            case 3:cplus.setVisible(true);x=449;
            break;
            case 4:c.setVisible(true);x=399;
            break;
            default:Qbasic.setVisible(true);x=299;
            break;}
        lb1.setText(Integer.toString(x));
        z=x*y;
        lb2.setText(Integer.toString(z));
    }//GEN-LAST:event_cbqMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Software().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String x=mainscreen.nm.getText();
        JOptionPane.showMessageDialog(this,"Thanks for visiting us.");
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject", "root", "tiger");
            Statement st=con.createStatement();
            String query="drop table "+x+";";
            st.executeQuery(query);}
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String i=(String) cb1.getSelectedItem();
        String y=(String) cbq.getSelectedItem();
        String x=lb2.getText();
        String n=mainscreen.nm.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject", "root", "tiger");
            Statement st=con.createStatement();
            String query="insert into "+n+"(Product,Quantity,Netamnt) values('"+i+"','"+y+"','"+x+"');";
            int d=st.executeUpdate(query);
            if(d>0)
            {
                JOptionPane.showMessageDialog(this,"item successfully added");
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programming().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Qbasic;
    private javax.swing.JLabel c;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cbq;
    private javax.swing.JLabel cplus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel nbeans;
    private javax.swing.JLabel python;
    // End of variables declaration//GEN-END:variables
}
